simple calculator.py
diwas7777/CodesHub pull request #286
Opened 2022-10-31 17:18 UTC by Ruteswar

2022-10-31 17:19 UTC, Ruteswar commented
this code is written to create simple calculator using python.

2022-10-31 17:39 UTC, Ruteswar commented
plz sir merge this

2022-11-01 01:17 UTC, ghost commented
please remove duplicates

2022-11-01 01:18 UTC, ghost requested changes
remove duplicated

2022-12-17 15:48 UTC, closed without merging